### ISSUE TITLE
course timeline component -> create course item component

### ISSUE THREAD

**Issue by michahell** [hyf-project5/hyfer#31]
<img src="https://cldup.com/3ROOYhRgyL.png"/>

The course item component:

- should have a parent dependancy (`require`) on the `course bar component`
- should have the following properties:
   - **color** (default: turqoise)
   - **shape** (default: rounded rectangle)
   - **enabled** (default: false)
   - **selected** (default: false)
- should be **clickable / tappable**
- ideally is a [transitional interface](https://medium.com/@pasql/transitional-interfaces-926eb80d64e3#.yjhoy240q) component !

**Comment by hasan-sh** [comment]
DONE
