### ISSUE TITLE
Find and try out several NPM github APIs

### ISSUE THREAD

**Issue by michahell** [hyf-project5/hyfer#33]
I already tried out one: https://github.com/michahell/hyf-github-example
- \+ nice, big API.
- \+ very easy to use, together with API documentation.
- \- not sure if there is another way to get the text content other than on a per-file basis and convert it to text using Base64 decoding.

**Comment by eidosam** [comment]
These are nice libraries for parsing _markdown_ and rendering to HTML
https://github.com/showdownjs/showdown
https://github.com/markdown-it/markdown-it
And the one @michahell mentioned above (for GitHub) is good and easy to use
https://github.com/mikedeboer/node-github

**Comment by eidosam** [comment]
Proposed by Jim Cramer @remarcmij
https://github.com/chjj/marked

**Comment by JackSacali** [comment]
@eidosam did you had time to test the APIs?

**Comment by JackSacali** [comment]
After testing the git API few times, I got this message: https://github.com/michahell/hyf-github-example
```
 [Error: {"message":"API rate limit exceeded for 87.214.232.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}]
  message: '{"message":"API rate limit exceeded for 87.214.232.122. (But here\'s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}',
  code: 403,
  status: 'Forbidden',
  headers:
```

**Comment by eidosam** [comment]
Good point @aboRoma 
Following guidance from https://developer.github.com/v3/#rate-limiting I updated the example @michahell created see: https://github.com/eidosam/hyf-github-example/blob/master/index.js
We can tackle the issue _API rate limit exceeded_ by authenticating API request, and/or checking _etag_ of content, by adding header `If-None-Match` to each request (etag/content should be stored/mapped in local-storage/database)
The other option is to use CI/CD tools on each repo contains the source-module-content:
- Content is served to user from server local-storage/database
- Content is updated on server via CI/CD tool on any change made on GitHub repo
