### ISSUE TITLE
COME UP WITH A NAME TO THE PROJECT

### ISSUE THREAD

**Issue by JackSacali** [hyf-project5/hyfer#40]

**Comment by JackSacali** [comment]
HYF School
HYF Virtual Learn
HYF Academy

**Comment by JackSacali** [comment]
Guys any suggestion could be OK 👎

**Comment by unmeshvrije** [comment]
HyForce:
1. It is nerdy
2. It starts with HYF
3. One can pronounce it as one word
4. It suggest strength
