### ISSUE TITLE
Make it nicer on mobile devices;)!

### ISSUE THREAD

**Issue by hasan-sh** [hyf-project5/hyfer#61]
Jack would you like to work on a responsive version of the timeline and the toolbar, and maybe the footer as well!?

**Comment by JackSacali** [comment]
For the toolbar I'll work on it tomorrow, for the footer it's already responsive and for the timeline I did minimize block's size as Jim suggested to fit in both mobiles and wide screens, still need to be a little bit smaller on mobile but that can not be done in few days.
